server:
  port: 8080

spring:
  application:
    name: currency_project_tbank

  datasource:
    url: jdbc:postgresql://user-db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
      change-log: classpath:db/changelog/db.changelog-master.sql

currency-tracker:
  cb-api-url: "https://www.cbr-xml-daily.ru/daily_json.js"